### ISSUE TITLE
questions/help related to i18n (hope you dont mind)

### ISSUE THREAD

**Issue by skylarthai** [datyayu/new-datyayu.xyz#1]
Hello, I'm still new to Vue but I really like it and would like to improve.

Right now I'm trying to add i18n to my website.. actually, I already did, but it's not persistent (meaning every time I go to a new page then it default back to original language), so I have been looking through like a hundred repos trying to find a good way to achieve this, and I believe your way is the best and most readable (although I find other parts of your code qutie confusing :P).

I'm now in the process of rewriting it based on your code, but I'm stuck and I would really appreciate if you might have time to share suggestions.

My code structure is:

src/App.vue
src/main.js
src/routes.js

src/i18n/index.js
src/i18n/en.json
src/i18n/th.json
src/i18n/[etc].json

src/components/localization.vue
src/components/[other].vue

src/views/[name].vue

src/store/index.js (I also thought I would need this, but based on your code it seems it's not necessary)

Some difference between your and my code is that I would like to put all translations into a single json file, and I would like to continue having the main.js and App.vue files because I feel your way of intializing is too confusing for me

So this is my new i18n/index.js (file heavily inspired by yours):

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'

export default ({ app, store }) => {
  Vue.use(VueI18n)

  let locale = 'en'
  if (process.BROWSER_BUILD) { // actually not sure why this process.BROWSER_BUILD is necessary, but guess can figure out later
    locale = localStorage.getItem('locale') || 'en'
  }

  const i18n = new VueI18n({
    locale: locale,
    fallbackLocale: 'en',
    messages: {
      en: require('./en.json'),
      th: require('./th.json')
    }
  })

  app.i18n = i18n
}
```

This is my src/main.js file:

```
import Vue from 'vue'
import i18n from './i18n/index.js'
import App from './App'
import VueRouter from 'vue-router'
import { routes } from './routes'
// import store from './store'

Vue.use(VueRouter)

const router = new VueRouter({
  mode: 'history',
  base: __dirname,
  routes
})

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  i18n,
  render: h => h(App)
})
```

I think the majority of my problems comes down to this file, because I'm pretty sure that I'm not obtaining/calling the i18n file correctly.. but not sure how to do.

And in my src/components/localization.vue file I have this (tried to integrate your code here as well):

```
<template>
[...]
<button @click="setLocale('en')">English</button> 
<button @click="setLocale('th')">Thai</button>
</template>
<script>
export default {
  name: 'localization',
  data () {
    return {
    }
  },
  methods: {
    setLocale (locale) {
      if (locale === this.$i18n.locale) {
        return
      }
      this.$i18n.locale = locale
      localStorage.setItem('locale', locale)
    }
  }
}
</script>
```

(I didn't include your 'computed enClass and esClass' because I believe they're not relevant for this but maybe I'm wrong..)

-----

I'm also not quite sure but I believe that the way I previously called my translations (like this `{{ $t('views.home.title') }}` ) won't work, and instead I should also adopt to using:

```
computed: {
    homeTitle() {
      return this.$t("views.home.title");
    }
```
Sorry for the very long post, I hope you can help but won't blame you if you feel it's too much trouble :)

**Comment by skylarthai** [comment]
I'm stupid, it works great..

I just had to delete `if (process.BROWSER_BUILD)` and then it worked perfectly without using any computed stuff and such :)

Thanks for open sourcing this code, really helped me a lot

**Comment by datyayu** [comment]
np, glad my code helped you!

By the way, the `process.BROWSER_BUILD` is used because I'm doing server-side rendering and, as you might know, localstorage isn't available on node. So basically I'm just telling the build process to skip the code inside the `if` when doing SSR and leave it when building it for the browser.

**Comment by skylarthai** [comment]
@datyayu I do wonder.. it seems like everyone use store (vuex) to handle i18n, and [there's even a popular package for this sole purpose](https://github.com/dkfbasel/vuex-i18n).. yet you don't, despite already using store for other parts of your application.

May I ask why? Would there be any benefit in using both store together with localstorage? I mean I think your way of doing it is a million times better, and it works perfectly.. I just feel confused why everyone else isn't doing it this way, and why so many people use store/vuex for their i18n.

**Comment by datyayu** [comment]
I think it comes down to personal preference and use case. 

Vuex provides a good way to keep the shared state in-sync between components, so I use it for data that may be shared between several components (like the posts or the current page number).
In my case, I just care about value when the site loads or when the user wants to change it. So I don't have a real reason to keep it in the store, that's why I don't. 

But maybe you could use the current locale to determinate if a certain feature must be shown or not, and also many people serialize the application state so it can be used on the server, so that may be why some people find useful to store it using vuex.

About the cross-tab stuff, I don't think vuex alone solves this problem as the store is just an on-memory object (meaning, not shared across tabs/windows). I personally didn't care about doing it because it really isn't a likely scenario for a portfolio site but if you want to do something like that for the locale you could accomplish it pretty easily by listening for the 'storage' event and triggering the locale change whenever the local-storage value is updated.

Here's more info if you want to know more:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

**Comment by skylarthai** [comment]
Oh wow, that makes a lot of sense, thanks a lot :)!
